name: Astro511
channels:
  - conda-forge
  - defaults
dependencies:
  - astroquery
  - astropy
  - numpy
  - numba
  - holoviews
  - scipy
  - pandas
  - pytables
  - matplotlib
  - h5py
  - ipykernel
  - gsl
  - gala
