name: Astro511
channels:
  - conda-forge
  - defaults
dependencies:
  - astroquery
  - astropy
  - numpy <= 1.23.5
  - numba
  - holoviews
  - scipy
  - pandas
  - pytables
  - matplotlib
  - h5py
  - ipykernel
  - gsl
  - gala
  - ipympl
  - plotly
  - ipywidgets
  - pip:
    - galpy
